#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.
gems:
  - jekyll-redirect-from
  - jekyll-feed

name: "The Blog of Joshua Cox"
description: "Where I blog about Jekyll, techronmancy, docker, and other usually linux related stuff"
url: http://joshuacox.github.io
author: Joshua Cox

#REQUIRED
org_site: joshuacox.github.io
org_url: https://joshuacox.github.io
org_name: Joshua Cox
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Techromancer
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Have Portable Penetration Testing Hardware - will travel

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: uberthoth@gmail.com
org_street_address: 1105 West Oltorf #Please include suite number on the line below
org_address_suite: Suite 100
org_city: Austin
org_state: TX
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  78704
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (512) 441-5269

#SOCIAL MEDIA
github_username: joshuacox
twitter_username: uberthoth
facebook_username: uberthoth
org_instagram_username: uberthoth

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: false

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: uberthoth

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: seven

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      disqus: true
      category: blog
      tags:
        - blog
#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
baseurl: /
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://joshuacox.github.io/'
  relativeLinks: 'http://joshuacox.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "photo_url"
        field:
          element: "text"
          label: "450x450 Picture Thumb for index"
          value: ""
      - name: "disqus"
        field:
          element: "checkbox"
          label: "Disqus Comments"
          value: true
      - name: "fbcomments"
        field:
          element: "checkbox"
          label: "Facebook Comments"
          value: false
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "category"
        field:
          element: "select"
          label: "Select Category"
          placeholder: "Choose Category"
          options:
            - name: "Docker"
              value: "docker"
            - name: "Linux"
              value: "linux"
            - name: "Jekyll"
              value: "jekyll"
            - name: "CLI"
              value: "cli"
            - name: "Blog Post"
              value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Docker"
              value: "docker"
            - name: "Linux"
              value: "linux"
            - name: "Jekyll"
              value: "jekyll"
            - name: "CLI"
              value: "cli"
            - name: "Humor"
              value: "humor"
            - name: "Ruby"
              value: "ruby"
            - name: "Javascript"
              value: "javascript"
            - name: "Python"
              value: "python"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
